name: mynotes
description: "A robust, cross-platform note-taking application built with **Flutter** and **Firebase**, utilizing the **BLoC (Business Logic Component)** pattern for scalable state management."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_analytics: ^12.1.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  path: ^1.9.0
  share_plus: ^12.0.1
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  test: ^1.26.3
  mockito: ^5.4.4

flutter:
